[build]
# Явно указываем использовать Docker
builder = "dockerfile"
dockerfile = "Dockerfile"

[deploy]
startCommand = "npm run preview"
prescriptCommand = "npm run build"

[env]
NODE_ENV = "production"
